### ISSUE TITLE
"Invalid header" when testing on HackRF One

### ISSUE THREAD

**Issue by kaedenbrinkman** [cho45/hackrf-sweep-webusb#3]
Device:
```
0000000000000000f75461dc2c946dc3
Board ID Number: 4 (undefined)
Firmware Version: 2023.01.1 (API:1.07)
Part ID Number: a000cb3c 006a4764
```
After pressing "start", I get the following output in the console:
```
invalid header 0 0 253
...
```
![image](https://github.com/cho45/hackrf-sweep-webusb/assets/49798040/89262a47-cf4d-4ac1-9c7c-dd0c7c147fc7)

**Comment by cho45** [comment]
This was due to changes in firmware implementation. I also updated to the latest firmware and encountered this issue  and made changes to fix this.
